services:
  app:
    image: 577638354424.dkr.ecr.ap-south-1.amazonaws.com/trv-sandbox-ui
    container_name: trv_sanbox_ui
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    env_file:
      - .env
    restart: always
