version: "3.8"
services:
  app:
    image: 577638354424.dkr.ecr.ap-south-1.amazonaws.com/staging/fis-sandbox-ui:latest
    container_name: ${CONTAINER_NAME}
    ports:
      - "${PORT}:80"
    env_file:
      - .env
    restart: always
